version: '3.10'

services:
  web:
    build:
      context: ./maps/
      dockerfile: ./Dockerfile
#    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - .:/web_django
    ports:
      - '8000:8000'


